### PR TITLE
Added media extension ala: https://docs.djangoproject.com/en/2.0/topi…

### LINKED ISSUE #23: Django 2.0 compatibility
Tabbed admin isn't working with Django 2.0. Probably because TabbedAdmin uses django.forms.Media.add_css() and django.forms.Media.add_js() functions, which do not exist in Django 2.0. 

Question - are there any plans on making TabbedAdmin compatible with Django 2.0?

### PR DESCRIPTION
**Pull request by ogtony**
Fixes #23

### CODE REVIEW

**Comment by cyberbudy** [comment]
Any progress on it?

**Comment by ogtony** [comment]
Are you asking me? 
I can tell you this branch works and I am using it in a beta Django 2.0 site just fine if you want to work off my commit until the maintainers come and look around.

**Comment by dfalling** [comment]
This works for me as well with Django 2.0.3.  Can we get some eyes on this by the maintainers?  I'd love to see this merged in.

**Comment by dctremblay** [comment]
I can't get it to work here. Am I doing it right ?

`Pipfile` :
```toml
[packages]
django-tabbed-admin = { git = 'https://github.com/omji/django-tabbed-admin.git', ref = '8bac5bf138bdbcc624708412b38f253c3cf04855' }
```

Then :
```bash
pipenv install --dev
```

In settings :
```python
TABBED_ADMIN_USE_JQUERY_UI = True
```

Getting this error message in the JS console :

```
(index):1440 Uncaught TypeError: $(...).tabs is not a function
    at (index):1440
    at (index):1475
(anonymous) @ (index):1440
(anonymous) @ (index):1475
```

How can I resolve this ?

Thanks !

**Comment by jox** [comment]
Works well here with Django 2.0.6 and Grappelli 2.11.1. Thanks!
Maintainers, please maintain! :-)

**Comment by Gedzis** [comment]
@omji can you merge this?

**Comment by omji** [comment]
Thanks a million guys! Sorry for the silence, but I have some insane workload nowadays. If anyone wants to take over some admin role on this project that would be awesome!

**Comment by omji** [comment]
I ll try to push a new version on Pypi today or tomorow! Thanks again!
